# Generated by Django 5.1.7 on 2025-04-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_itempedido_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='qtd_total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
