# Generated by Django 4.2.16 on 2024-11-04 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact_teste",
        ),
    ]
