# Generated by Django 4.2.16 on 2024-11-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_delete_contact_teste"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="picture",
            field=models.ImageField(blank=True, upload_to="pictures/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="contact",
            name="show",
            field=models.BooleanField(default=True),
        ),
    ]
