# Generated by Django 5.1.7 on 2025-03-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_variacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao_longa',
            field=models.TextField(default=''),
        ),
    ]
